[filter_scheduler]
pci_in_placement = true
enabled_filters = ComputeFilter,ComputeCapabilitiesFilter,ImagePropertiesFilter,ServerGroupAntiAffinityFilter,ServerGroupAffinityFilter,PciPassthroughFilter
available_filters = nova.scheduler.filters.all_filters

[pci]
report_in_placement = true
alias = {"name": "nvidia_gpu6gb", "vendor_id": "10de", "product_id": "2191", "resource_class": "CUSTOM_PCI_10DE_2191"}
