[filter_scheduler]
pci_in_placement = true


[pci]
report_in_placement = true
device_spec = {"vendor_id": "10de", "product_id": "2191", "device_type": "type-PCI", "dev_type": "type-PCI"}

[DEFAULT]
resume_guests_state_on_host_boot = True