[DEFAULT]
enabled_backends = lvm-nvme, lvm-ssd, lvm-hdd

[lvm-nvme]
volume_backend_name = lvm-nvme
volume_driver = cinder.volume.drivers.lvm.LVMVolumeDriver
volume_group = cinder-volumes-nvme-ssd
target_helper = tgtadm

[lvm-ssd]
volume_backend_name = lvm-ssd
volume_driver = cinder.volume.drivers.lvm.LVMVolumeDriver
volume_group = cinder-volumes-sata-ssd
target_helper = tgtadm

[lvm-hdd]
volume_backend_name = lvm-hdd
volume_driver = cinder.volume.drivers.lvm.LVMVolumeDriver
volume_group = cinder-volumes-hdd
target_helper = tgtadm