[DEFAULT]
# Tell Cinder to use two specific backends
enabled_backends = lvm-nvme, lvm-ssd, lvm-hdd

[lvm-nvme]
volume_backend_name = NVME_Storage
volume_driver = cinder.volume.drivers.lvm.LVMVolumeDriver
volume_group = cinder-volumes-nvme-ssd
target_helper = tgtadm

[lvm-ssd]
volume_backend_name = SSD_Storage
volume_driver = cinder.volume.drivers.lvm.LVMVolumeDriver
volume_group = cinder-volumes-sata-ssd
target_helper = tgtadm

[lvm-hdd]
volume_backend_name = HDD_Storage
volume_driver = cinder.volume.drivers.lvm.LVMVolumeDriver
volume_group = cinder-volumes-hdd
target_helper = tgtadm