[DEFAULT]
# Enable the cinder backend
enabled_backends = cinder_hdd:cinder

[glance_store]
# Set the default store to our new cinder backend
default_backend = cinder_hdd

[cinder_hdd]
cinder_volume_type = ncs-hdd
cinder_store_project_name = service
cinder_store_user_name = glance
cinder_store_password = {{ glance_keystone_password }}
cinder_store_auth_address = {{ keystone_internal_url }}
cinder_os_region_name = {{ openstack_region_name }}
cinder_store_project_domain_name = Default
cinder_store_user_domain_name = Default