[router] 
OpenWrt ansible_host=172.16.0.1  ansible_user=root

[baremetal]
node-01 ansible_host=node-01.lan mgmt_interface=eno1 provider_interface=vlan20@eno1 ansible_user=ubuntu
node-02 ansible_host=node-02.lan mgmt_interface=eno1 provider_interface=vlan20@eno1 ansible_user=ubuntu
node-03 ansible_host=node-03.lan mgmt_interface=enp5s0 provider_interface=vlan20@enp5s0 ansible_user=ubuntu

[baremetal_gpu]
node-02 ansible_host=node-02.lan mgmt_interface=eno1 provider_interface=vlan20@eno1 ansible_user=ubuntu
