- name: Create New Project and User in Edmonton Lab
  hosts: localhost
  connection: local
  vars_files:
    - secrets.yaml
  module_defaults:
    group/openstack.cloud.openstack:
      auth:
        auth_url: "{{cloud_url}}:5000/v3"
        username: "admin"
        password: "{{ vault_keystone_admin_password }}"
        project_name: "admin"
        user_domain_name: "Default"
        project_domain_name: "Default"
  tasks:
    - name: Create the Dev-Project
      openstack.cloud.project:
        name: dev-project
        description: "Sandbox for non-ML tasks"
        state: present

    - name: Set Quotas for the new Dev-Project
      openstack.cloud.quota:
        cloud: kolla-admin
        name: dev-project
        cores: 10
        ram: 16384
        gigabytes: 500
        volumes: 10

    - name: Create a new User
      openstack.cloud.identity_user:
        cloud: kolla-admin
        name: lab-assistant
        password: "TemporaryPassword123!"
        domain: default
        state: present

    - name: Assign the user to the project with a role
      openstack.cloud.role_assignment:
        cloud: kolla-admin
        user: lab-assistant
        project: dev-project
        role: member