---
- name: Restrict Storage Tiers for Dev Project
  hosts: localhost
  connection: local
  vars_files:
    - secrets.yaml
  
  module_defaults:
    group/openstack.cloud.openstack:
      auth:
        auth_url: "{{ cloud_url }}:5000/v3"
        username: "admin"
        password: "{{ vault_keystone_admin_password }}"
        project_name: "admin"
        user_domain_name: "Default"
        project_domain_name: "Default"

  tasks:
    - name: Source admin credentials and set quotas
      shell: |
        source ../etc/kolla/admin-openrc.sh
        openstack quota set --volume-type NVMe_Tier --gigabytes 0 dev-project
        openstack quota set --volume-type SSD_Tier --gigabytes 0 dev-project
        openstack quota set --volume-type HDD_Massive_Tier --gigabytes 500 dev-project
      args:
        executable: /bin/bash