ansible_ssh_user: ubuntu
docker_custom_config:
  data-root: "/var/lib/docker" # Keep Docker on the os ssd


physical_network_interface: "eno1"
# api_interface: "eno1"
# storage_interface: "eno1"
# tunnel_interface: "eno1"

